name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Cache
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo

      - name: Add cross compile Linux tools
        env:
          packages: >-
            build-essential
            cmake
            perl
            curl
            clang
            libssl-dev
            librocksdb-dev
            protobuf-compiler
            musl-dev
            musl-tools
            llvm
            python3-pip
        run: |
          apt update -yq
          apt install -yq $packages
          PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install ziglang

          rustup target add ${{ matrix.target }}

      - name: Build
        run: |
          cargo zigbuild -r --target ${{ matrix.target }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            target/${{ matrix.target }}/release/linker-experiments
          tag_name: rc-${{ github.ref_name }}-${{ github.run_number }}
