name: Build

on:
  push:
    branches:
      - main
      - ci/*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Cache
      - name: Setup cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: builder-${{ runner.os }}-cargo

      - name: Setup pip cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/pip/
          key: builder-${{ runner.os }}-pip

      - name: Add cross compile Linux tools
        env:
          packages: >-
            build-essential
            cmake
            curl
            clang
            librocksdb-dev
            protobuf-compiler
            llvm
            python3-pip
        run: |
          sudo apt update -yq
          sudo apt install -yq $packages
          type zig || pip3 install ziglang

          rustup target add ${{ matrix.target }}
          test -f ~/.cargo/bin/cargo-zigbuild || cargo install cargo-zigbuild
        shell: bash

      - name: Build
        run: |
          cargo zigbuild -r --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/linker-experiments linker-experiments-${{ matrix.target }}
          tar czvf linker-experiments-${{ matrix.target }}.tar.gz linker-experiments-${{ matrix.target }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            linker-experiments-${{ matrix.target }}
          tag_name: rc-${{ github.ref_name }}-${{ github.run_number }}
